language: node_js
node_js:
  - "8.11.4"
before_install:
  - cd ClinicWeb
script:
  - ng lint
  - ng build --prod
install:
  - npm install --save-dev @angular-devkit/build-angular
  - npm install -g @angular/cli
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token 1/gZZjbfzz7vjcb8vgm8pUqz1nOXeDasBcT_NsxDsnQBU