language: node_js
node_js:
  - "8.11.4"
script:
  - ng lint
  - ng build --prod
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token 1/gZZjbfzz7vjcb8vgm8pUqz1nOXeDasBcT_NsxDsnQBU