// <auto-generated />
namespace Clinic.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddRateForBookingTableUpdateRateTypeInClinicianTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRateForBookingTableUpdateRateTypeInClinicianTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201903082118059_AddRateForBookingTableUpdateRateTypeInClinicianTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
